function [fitresult, gof, coeff] = createFit1(xAxDilsRow, var1)
%CREATEFIT1(XAXDILSROW,VAR1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xAxDilsRow
%      Y Output: var1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Jun-2021 11:40:13


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xAxDilsRow, var1 );

% Set up fittype and options.
ft = fittype( '-a/(1+exp((-x+c)/b))+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [-3 1 -9 3];
% StartPoints
% [3 1 3 6] when using dilution factor
% [-3 1 -9 3] when using actual concentration (Molarity)

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
coeff = coeffvalues(fitresult);

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'var1 vs. xAxDilsRow', 'untitled fit 1', 'Location', 'NorthWest', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'xAxDilsRow', 'Interpreter', 'none' );
% ylabel( 'var1', 'Interpreter', 'none' );
% grid on


